export const projects = [
    {
        name: 'IP Management System',
        image: 'itsoip.png',
        description: 'A PWA Built to Streamline Intellectual Property Protection Application Workflows for ITSO at UIC.',
        tags: ['PWA', 'Laravel', 'Software Engineering'],
        role: 'Full-Stack Developer',
        features: ['IP application workflow', 'Status tracking', 'Document handling for submissions'],
        outcome: 'Supported a more efficient and organized IP filing process.',
        category: 'Web',
        featured: true,
    },
    {
        name: 'RPIC Research Management',
        image: 'rpic.jpg',
        description: 'A PWA for Research Defense Scheduling, Document Storage, and Publication and Seminar Information Management.',
        tags: ['PWA', 'MySQL', 'PAASCU Support'],
        role: 'Backend and Database Developer',
        features: ['Defense schedule management', 'Research document repository', 'Information access for seminars and publications'],
        outcome: 'Improved compliance support and organizer efficiency for research activities.',
        category: 'Web',
        featured: false,
    },
    {
        name: 'UIC DOST Scholar Management System',
        image: 'dost.jpg',
        description: 'A Web-Based System for Managing UIC DOST Scholar Records, Requirements, and Status Tracking Workflows.',
        tags: ['Laravel', 'MySQL', 'Scholarship Management'],
        role: 'Full-Stack Developer',
        features: ['Scholar profile management', 'Requirement and compliance tracking', 'Status monitoring dashboard'],
        outcome: 'Centralized scholar operations and reduced manual tracking overhead for coordinators.',
        category: 'Web',
        featured: true,
    },
    {
        name: 'Anime Dojo Game',
        image: null,
        description: 'An Interactive Gaming PWA Integrated with Trained AI Models to Predict Outcomes and Provide User Insights.',
        tags: ['AI', 'JavaScript', 'Node.js'],
        role: 'Game Systems Developer',
        features: ['AI-assisted prediction engine', 'Session-based scoring', 'Interactive gameplay loops'],
        outcome: 'Delivered a more engaging and personalized player experience.',
        category: 'Web',
        featured: false,
    },
    {
        name: 'Guide to Loratadine (Allerta)',
        image: 'alerta.jpg',
        description: 'A Mobile Application That Educates Users About Loratadine Mechanisms and Effects in the Body.',
        tags: ['Mobile', 'Health Education', 'IT Elective'],
        role: 'Mobile App Developer',
        features: ['Drug mechanism overview', 'Educational mobile interface', 'Structured health information'],
        outcome: 'Provided a student-focused health learning resource in mobile format.',
        category: 'Mobile',
        featured: false,
    },
    {
        name: 'NeuroZen',
        image: 'neurozen.png',
        description: 'A Mobile Prototype for Stress Management with a Simulated Marketplace for Wellness Products.',
        tags: ['Mobile', 'Prototype', 'Wellness'],
        role: 'Prototype Developer',
        features: ['Stress-management concept screens', 'Simulated product marketplace', 'Mobile-first user journey'],
        outcome: 'Validated a practical concept for wellness-oriented mobile experiences.',
        category: 'Mobile',
        featured: false,
    },
    {
        name: 'TUN-AN Landing Page',
        image: 'tun-an.jpg',
        description: 'A Corporate Landing Page for a Technopreneurship Company with an Integrated Email Inquiry Workflow.',
        tags: ['Landing Page', 'Email Integration', 'Technopreneurship'],
        role: 'Frontend and Integration Developer',
        features: ['Corporate brand layout', 'Email inquiry handling', 'Customer-service contact flow'],
        outcome: 'Improved customer inquiry handling and online company visibility.',
        category: 'Web',
        featured: false,
    },
    {
        name: 'Clinic-Connect',
        image: 'clinicconnect.jpg',
        description: 'A Pediatric Care Appointment PWA for Booking, Consultations, and Medication Purchasing.',
        tags: ['PWA', 'Healthcare', 'Appointments'],
        role: 'Full-Stack Developer',
        features: ['Appointment booking system', 'Consultation queue management', 'Medication catalog and ordering'],
        outcome: 'Centralized pediatric care workflows for patients and clinic staff.',
        category: 'Web',
        featured: false,
    },
    {
        name: 'Ayo-ayo AI Green Computing',
        image: 'ayoayo.jpg',
        description: 'An AI-Integrated Mobile App Promoting E-Waste Mitigation Through Recycle, Donate, and Sell Flows.',
        tags: ['AI', 'Mobile', 'Sustainability'],
        role: 'Mobile and API Integrator',
        features: ['Recycling and donation flows', 'Sell feature for reusable electronics', 'Knowledge-sharing prompts'],
        outcome: 'Encouraged practical e-waste awareness and action through a user-friendly app.',
        category: 'Mobile',
        featured: false,
    },
    {
        name: 'Public Health Research Forum Materials',
        image: 'public-health.jpg',
        description: 'Designed Publication Materials for the University of the Immaculate Conception Public Health Research Forum 2024.',
        tags: ['Publication Design', 'Academic Event', '2024'],
        role: 'Publication Designer',
        features: ['Visual communication assets', 'Event publication layout', 'Consistent branding support'],
        outcome: 'Supported event communication and participant engagement.',
        category: 'Design',
        featured: false,
    },
    {
        name: 'House Rental System',
        image: null,
        description: 'A Personal PWA for Rental Listing Management and Tenant Tracking.',
        tags: ['PWA', 'Property Management', 'Personal Project'],
        role: 'Full-Stack Developer',
        features: ['Listing and tenant management', 'Rental status dashboard', 'Record maintenance module'],
        outcome: 'Simplified rental operations and reduced manual property tracking tasks.',
        category: 'Web',
        featured: false,
    },
    {
        name: 'UIC Digital Christmas Tree',
        image: 'xmas.jpg',
        description: 'A Web Application Commemorating 2025 University Events with Interactive Ornaments and 2026 Resolution Sharing.',
        tags: ['Interactive Web App', 'Community', 'Personal Project'],
        role: 'Frontend Developer',
        features: ['Interactive ornament placement', 'Resolution sharing flow', 'Event-themed visual design'],
        outcome: 'Created an engaging and memorable digital year-end experience for users.',
        category: 'Web',
        featured: true,
    },
    {
        name: 'UIC Valentine Wall',
        image: 'valentine.jpg',
        description: 'An Interactive Wall Web App Where Users Can Post and View Digital Valentine Messages for the UIC Community.',
        tags: ['Interactive Web App', 'Community', 'Event Project'],
        role: 'Frontend Developer',
        features: ['Message posting flow', 'Community message wall', 'Event-themed interaction design'],
        outcome: 'Boosted community participation through a playful and memorable campus event experience.',
        category: 'Web',
        featured: false,
    },
    {
        name: 'Personal Portfolio Website',
        image: 'portfolio.jpg',
        description: 'A Personal Web Application Presenting Professional Background, Projects, Affiliations, and Services.',
        tags: ['Portfolio', 'Svelte', 'Laravel'],
        role: 'Designer and Developer',
        features: ['Project showcase', 'Leadership and achievements timeline', 'Contact and resume sections'],
        outcome: 'Strengthened professional branding for internship and job applications.',
        category: 'Web',
        featured: false,
    },
    {
        name: 'NASA Data Weather Forecast App',
        image: 'nasaapp.png',
        description: 'An AI-Integrated Mobile App Using NASA Data to Provide Weather Safety Insights for Hikers and Adventurers.',
        tags: ['AI', 'NASA Data', 'Mobile'],
        role: 'Mobile and AI Integrator',
        features: ['Weather safety insights', 'Adventure-oriented risk prompts', 'Data-driven mobile recommendations'],
        outcome: 'Developed for the NASA Space Apps Challenge 2025 with global challenge context.',
        category: 'Mobile',
        featured: false,
    },
    {
        name: 'Book-It-Now',
        image: 'book-it-now.png',
        description:
            'Book-It-Now is a Booking System Designed Specifically for the ICTDU (Information and Communications Technology Development Unit) at the University of the Immaculate Conception (UIC). It Streamlines the Process for Officers and the Secretary, Making it Easier to Access, Manage, and Coordinate the Utilization of ICTDU Resources Efficiently.',
        tags: ['Java', 'MySQL', 'Booking System', 'ICTDU Support'],
        role: 'Backend and Database Developer',
        features: ['Resource booking workflow', 'Officer and secretary coordination tools', 'Scheduling and utilization management'],
        outcome: 'Improved ICTDU resource coordination through a more organized and efficient booking process.',
        category: 'Web',
        featured: false,
    },
];
